### ISSUE TITLE
Github Signup Error

### ISSUE THREAD

**Issue by rr-iitp24** [AntonioErdeljac/next13-spotify#3]
When I am trying to signup with github account, nothing is happening and the url is showing following error:
http://localhost:3000/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODU1NDUwMzIsInNpdGVfdXJsIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIiwiaWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJmdW5jdGlvbl9ob29rcyI6bnVsbCwicHJvdmlkZXIiOiJnaXRodWIiLCJyZWZlcnJlciI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMC8iLCJmbG93X3N0YXRlX2lkIjoiYmM1MTZiMTctMDg4OC00ZGExLWE2YzktYmY5NmNmNWIzMzZhIn0.dSW7A_KqNmdMGLa8q505k02l643ybvcpRB9TfjzKS9c

This is my github oauth spotify settings:
![image](https://github.com/AntonioErdeljac/next13-spotify/assets/133568000/786fdbe2-39f2-4591-83ea-720fe07eae57)

**Comment by DariusLukasukas** [comment]
It seems that you have mistakenly configured the Authorization Callback URL to be "localhost:3000" instead of using the Supabase auth provider redirect URL.

To resolve this issue, you'll need to update the Authorization Callback URL in the Github settings to match the correct Supabase auth provider redirect URL. This URL is typically provided by Supabase during the authentication setup process and is specific to your application.

**Comment by rr-iitp24** [comment]
Thanks a lot. :)
